BEGIN;

-- 1. Modify the handle_new_user trigger to exclude Code Finder users
CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path = public, pg_temp
AS $function$
BEGIN
  IF COALESCE(
      NEW.raw_app_meta_data ->> 'account_type',
      ''
  ) <> 'code_finder' 
  AND LOWER(COALESCE(NEW.email, '')) NOT LIKE '%@codefinder.local'
  THEN
      INSERT INTO public.user_roles (id, username, role, is_active)
      VALUES (
        NEW.id,
        SPLIT_PART(NEW.email, '@', 1),
        'STAFF',
        true
      );
  END IF;

  RETURN NEW;
END;
$function$;

REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;

-- 2. Create the Code Finder User table
CREATE TABLE public.code_finder_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    auth_user_id UUID NOT NULL UNIQUE
        REFERENCES auth.users(id)
        ON DELETE RESTRICT,

    username TEXT NOT NULL
        CHECK (LENGTH(TRIM(username)) BETWEEN 1 AND 50),
    client_name TEXT NOT NULL
        CHECK (LENGTH(TRIM(client_name)) BETWEEN 1 AND 150),
    contact_person TEXT
        CHECK (
            contact_person IS NULL
            OR LENGTH(TRIM(contact_person)) BETWEEN 1 AND 150
        ),
    mobile TEXT,

    laminea_client_id UUID
        REFERENCES public.clients(id)
        ON DELETE SET NULL,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    must_change_password BOOLEAN NOT NULL DEFAULT TRUE,

    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX code_finder_users_username_unique
ON public.code_finder_users (
    UPPER(REGEXP_REPLACE(TRIM(username), '\s+', '', 'g'))
);

CREATE TRIGGER code_finder_users_updated_at
BEFORE UPDATE ON public.code_finder_users
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at();

-- 3. Create Enquiries table
CREATE TABLE public.code_finder_enquiries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    enquiry_number BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,

    code_finder_user_id UUID NOT NULL
        REFERENCES public.code_finder_users(id)
        ON DELETE RESTRICT,

    status TEXT NOT NULL DEFAULT 'NEW'
        CHECK (status IN (
            'NEW',
            'UNDER_REVIEW',
            'AWAITING_CLIENT',
            'CONFIRMED',
            'CONVERTED_TO_ESTIMATE',
            'REJECTED',
            'CANCELLED'
        )),

    client_note TEXT
        CHECK (
            client_note IS NULL
            OR LENGTH(client_note) <= 2000
        ),
    internal_note TEXT
        CHECK (
            internal_note IS NULL
            OR LENGTH(internal_note) <= 5000
        ),

    converted_estimate_id UUID
        REFERENCES public.estimates(id)
        ON DELETE SET NULL,

    checked_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT code_finder_enquiries_id_user_unique UNIQUE (id, code_finder_user_id)
);

CREATE TRIGGER code_finder_enquiries_updated_at
BEFORE UPDATE ON public.code_finder_enquiries
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at();

CREATE INDEX code_finder_enquiries_user_created_idx
ON public.code_finder_enquiries
(code_finder_user_id, created_at DESC);

CREATE INDEX code_finder_enquiries_status_idx
ON public.code_finder_enquiries(status);

CREATE UNIQUE INDEX code_finder_enquiries_estimate_unique
ON public.code_finder_enquiries(converted_estimate_id)
WHERE converted_estimate_id IS NOT NULL;


-- 4. Create Enquiry Items table
CREATE TABLE public.code_finder_enquiry_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    enquiry_id UUID NOT NULL
        REFERENCES public.code_finder_enquiries(id)
        ON DELETE CASCADE,

    alternative_code_snapshot TEXT NOT NULL
        CHECK (
            LENGTH(TRIM(alternative_code_snapshot)) BETWEEN 1 AND 100
        ),
    requested_quantity NUMERIC(12,2) NOT NULL
        CHECK (requested_quantity > 0),

    availability_status TEXT NOT NULL
        CHECK (availability_status IN (
            'AVAILABLE',
            'PLEASE_CONFIRM',
            'CODE_NOT_FOUND'
        )),

    checked_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX code_finder_enquiry_items_enquiry_idx
ON public.code_finder_enquiry_items(enquiry_id);

-- 5. Create Messages table
CREATE TABLE public.code_finder_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    code_finder_user_id UUID NOT NULL
        REFERENCES public.code_finder_users(id)
        ON DELETE CASCADE,

    enquiry_id UUID,

    sender_type TEXT NOT NULL
        CHECK (sender_type IN ('CLIENT', 'STAFF', 'SYSTEM')),

    sender_auth_user_id UUID
        REFERENCES auth.users(id)
        ON DELETE SET NULL,

    message TEXT NOT NULL
        CHECK (
            LENGTH(TRIM(message)) BETWEEN 1 AND 2000
        ),

    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    FOREIGN KEY (enquiry_id, code_finder_user_id)
        REFERENCES public.code_finder_enquiries(id, code_finder_user_id)
        ON DELETE RESTRICT
);

CREATE INDEX code_finder_messages_user_created_idx
ON public.code_finder_messages
(code_finder_user_id, created_at);

CREATE INDEX code_finder_messages_enquiry_idx
ON public.code_finder_messages(enquiry_id)
WHERE enquiry_id IS NOT NULL;


-- 6. Enable RLS and Restrict Access
ALTER TABLE public.code_finder_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.code_finder_enquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.code_finder_enquiry_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.code_finder_messages ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.code_finder_users FROM anon, authenticated;
REVOKE ALL ON public.code_finder_enquiries FROM anon, authenticated;
REVOKE ALL ON public.code_finder_enquiry_items FROM anon, authenticated;
REVOKE ALL ON public.code_finder_messages FROM anon, authenticated;

COMMIT;
